<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../DAOrganizer.Core/DAOrganizer.Core.csproj"/><ProjectReference Include="../../vendor/Arbiter/Arbiter.Net/Arbiter.Net.csproj"/><ProjectReference Include="../../vendor/Arbiter/Arbiter.Interop/Arbiter.Interop.csproj"/><ProjectReference Include="../../vendor/Arbiter/Arbiter.IO/Arbiter.IO.csproj"/></ItemGroup></Project>
